name: ntpr_vault
description: Ntpr Vault - secure key storage with notifications
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
